name: Synchronize Master to Dev

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request from master to dev
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Synchronize master to dev'
          branch: sync-master-to-dev
          base: dev
          title: 'Update dev branch with latest changes from master'
          body: |
            This pull request merges the latest changes from the master branch into the dev branch.
            
            **Changes:**
            - List of changes or features
            - Another change or feature
          delete-branch: true