name: Synchronize Master to Dev

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  upload-repository:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: .

  create-pull-request:
    runs-on: ubuntu-latest
    needs: upload-repository

    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo

      - name: Create pull request from master to dev
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Synchronize master to dev'
          branch: sync-master-to-dev
          base: dev
          title: 'Synchronize master to dev'
          body: 'This is an automated pull request to merge changes from master to dev.'
          delete-branch: true