name: Synchronize Master to Dev

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request from master to dev
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Synchronize master to dev'
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: master
          base: dev
          title: 'Update dev branch with latest changes from master as Synchronize master to dev'
          body: |
            This pull request merges the latest changes from the master branch into the dev branch.